services:
  - type: web
    name: overhead
    runtime: node
    plan: free
    buildCommand: "true"
    startCommand: npm start
  - type: web
    name: lastlie
    runtime: node
    plan: free
    buildCommand: "true"
    startCommand: npm run start:lastlie
